### ISSUE TITLE
program status

### ISSUE THREAD

**Issue by ynikitenko** [A-lxe/yarsync#1]
Hi, @reasonablytall ! Thanks for your tool.
I just wondered, do you still use that? 
The fact is that I developed a program with exactly the same name :(
While it's fine for github, I wanted to publish it in AUR, but the name is taken by your package.
So I decided to ask you first. If you still use the repo, then I should think of a new name.
Thanks!

**Comment by reasonablytall** [comment]
I don't use this tool anymore, so go ahead and take the name in the AUR :)

It doesn't seem to be in the [package list](https://archlinux.org/packages/?sort=&q=yarsync&maintainer=&flagged=), so I think you can just grab it? Let me know if there's anything I need to do to free up the name.

**Comment by ynikitenko** [comment]
Many thanks! No, I can't just use this existing package. I wrote to trusted users (made a delete request on AUR and linked to your agreement here), see what they will say. Thanks for the quick reply!

**Comment by ynikitenko** [comment]
And this is the link to your package (I probably should had posted it before). Maybe you could just delete it yourself?
https://aur.archlinux.org/packages/yarsync

**Comment by reasonablytall** [comment]
I disowned the package -- I think you should be able to adopt it.

**Comment by ynikitenko** [comment]
Yes, I managed to own it and pushed my package there. Now it all works. I wrote a comment that that is a very different package now (https://aur.archlinux.org/packages/yarsync#comment-872103). Many thanks for your very fast help again! 

BTW, if you don't need a continuous synchronization tool, you may have a look at my program for synchronization on user request (https://github.com/ynikitenko/yarsync). Hope this would be useful for someone.
